import React from 'react';
import ReactMarkdown from 'react-markdown';
import './PrintTemplate.css';

const PrintTemplate = React.forwardRef(({ report, medicalPart }, ref) => {
  if (!report) return null;

  return (
    <div className="pdf-print-wrapper" style={{ position: 'absolute', top: '-9999px', left: '-9999px' }}>
      <div ref={ref} className="pdf-print-container">
        
        <header className="pdf-header">
          <div className="pdf-brand">
            <h2>🏥 HealthReport AI</h2>
            <p>Smart Medical Analysis System</p>
          </div>
          <div className="pdf-meta">
            <p><strong>Patient/Report:</strong> {report.filename}</p>
            <p><strong>Date Analyzed:</strong> {new Date(report.date).toLocaleDateString('en-US', {
              year: 'numeric', month: 'long', day: 'numeric'
            })}</p>
          </div>
        </header>

        <hr className="pdf-divider" />

        <main className="pdf-content">
          <ReactMarkdown>{medicalPart}</ReactMarkdown>
        </main>

        <footer className="pdf-footer">
          <p><em>Disclaimer: This report is generated by an AI (HealthReport AI). It is intended for informational purposes only. Please consult a qualified healthcare professional before making any medical decisions.</em></p>
          <p className="pdf-page-number">Generated on {new Date().toLocaleDateString()}</p>
        </footer>

      </div>
    </div>
  );
});

export default PrintTemplate;
